### ISSUE TITLE
Patterns file HMSS2

### ISSUE THREAD

**Issue by ckeuschn** [TSTanabe/HMSS2#3]
Hi, I just started to explore this great tool, thanks a lot! Does the pattern file for the new version of the software also include the organosulfur pathways? And is there an option to output all proteins or keywords in the database or does one have to define it by hand with for example the -dfk option? 
Thanks a lot
Christoph

**Comment by TSTanabe** [comment]
Dear Christoph,

currently you can only View and modify the Patterns File via an Editor. You
can find IT in the src folder of HMSS2 and add the Patterns you require.
I dont know why I did not think of adding an option to print the patterns
earlier. Will be included in the next Update.
I am currently also working on the implementation of a method to
automatically detect gene clustern from the hmmsearch results.
Let me know If I can help

Best

Sebastian

ckeuschn ***@***.***> schrieb am Mo., 3. Juni 2024, 17:03:

**Comment by ckeuschn** [comment]
Hi Sebastian, 

thanks for your answer, I will modify the patterns file accordingly. I think it is great that one can use the created database to generate all kinds of output. For some users a general "all_hmms_vs_all_genomes" matrix output could be interesting to get an overview when you start out on a dataset. Great that you keep on working and improving that, definitely will use it :) 

Christoph
